---
- name: Include vars
  include_vars: main.yml

- name: Install kexec-tools
  package: name=kexec-tools state=present

- name: Find out reserved memory for the crash kernel
  command: cat /sys/kernel/kexec_crash_size
  register: kexec_crash_size

- name: Show value of kexec_crash_size for debugging
  debug: var=kexec_crash_size verbosity=0

- name: copy id_rsa
  copy:
    src: /root/.ssh/kdump_id_rsa
    dest: "{{ ssh_private_key }}"
    owner: root
    group: root
    mode: 0600
  when: ssh_server is defined and ssh_server != ''

- name: register the status of /etc/kdump.conf
  stat: path=/etc/kdump.conf
  register: stat_conf

- name: Make backup of /etc/kdump.conf if existed
  copy: src=/etc/kdump.conf dest=/etc/kdump.conf.backup
  when: stat_conf.stat.exists == True and kdump_conf_changed

- name: Generate /etc/kdump.conf file
  template: src=kdump.conf.j2 dest=/etc/kdump.conf
  when: kexec_crash_size.stdout|int > 0 and kdump_conf_changed
  notify: restart kdump

- name: Add header to /etc/kdump.conf
  lineinfile:
    dest: /etc/kdump.conf
    regexp: '# Last modified:'
    state: present
    insertbefore: BOF
    line: "# Last modified: {{ ansible_date_time.date }} {{ ansible_date_time.time }}\n"
  when: kdump_conf_changed

- name: register the status of /etc/sysconfig/kdump
  stat: path=/etc/sysconfig/kdump
  register: stat_conf

- name: Make backup of /etc/sysconfig/kdump
  copy: src=/etc/sysconfig/kdump dest=/etc/sysconfig/kdump.backup
  when: stat_conf.stat.exists == True and kdump_sysconfig_changed

- name: Generate /etc/sysconfig/kdump file
  template: src=kdump.j2 dest=/etc/sysconfig/kdump
  when: kexec_crash_size.stdout|int > 0 and kdump_sysconfig_changed
  notify: restart kdump

- name: Add header to /etc/sysconfig/kdump
  lineinfile:
    dest: /etc/sysconfig/kdump
    regexp: '# Last modified:'
    state: present
    insertbefore: BOF
    line: "# Last modified: {{ ansible_date_time.date }} {{ ansible_date_time.time }}\n"
  when: kdump_sysconfig_changed

- name: Enable kdump
  service: name=kdump state=started enabled=yes

